#!/usr/bin/env node
/**
 * Generate public/feed.xml (Atom) from the blog itself.
 *
 * The house rules promise no newsletter and no tracking, which leaves exactly
 * one honest way to follow the blog: a feed the reader pulls, on their
 * schedule, telling us nothing. This is that file.
 *
 * Every fact in the feed already exists on the pages — the generator reads the
 * BlogPosting JSON-LD each post carries for structured data and copies it, so
 * a post cannot say one thing to a search engine and another to a reader. The
 * order is the blog index's order (the launch series in reading order, then
 * the guides), because that is the editorial sequence a person should meet
 * them in; feed readers re-sort by date regardless.
 *
 * Zero dependencies, run by hand and pinned by test/seo.test.js:
 *   node scripts/build-feed.js          write public/feed.xml
 *   node scripts/build-feed.js --check  exit 1 if it is out of date
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const pub = (file) => path.join(root, 'public', file);
const SITE = 'https://mysovereign.ai';
const TITLE = 'The SovereignAI blog';
const SUBTITLE = 'Owning your AI: what runs on your machine, what leaves it, and what that costs.';

const escape = (text) =>
  String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** The posts, in the order the blog index lists them. */
export function readPosts() {
  const index = fs.readFileSync(pub('blog.html'), 'utf8');
  const slugs = [...new Set([...index.matchAll(/href="\/blog\/([a-z0-9-]+)"/g)].map((m) => m[1]))];
  const files = fs.readdirSync(pub('.')).filter((f) => /^blog-.+\.html$/.test(f));
  // A post the index forgot to link would silently vanish from the feed, so
  // it is an error here rather than an absence there.
  const missing = files.filter((f) => !slugs.includes(f.replace(/^blog-/, '').replace(/\.html$/, '')));
  if (missing.length) throw new Error(`the blog index does not link: ${missing.join(', ')}`);

  return slugs.map((slug) => {
    const file = `blog-${slug}.html`;
    const html = fs.readFileSync(pub(file), 'utf8');
    const block = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
    if (!block) throw new Error(`${file} carries no JSON-LD to build a feed entry from`);
    const data = JSON.parse(block[1]);
    if (data['@type'] !== 'BlogPosting') throw new Error(`${file} does not declare a BlogPosting`);
    for (const field of ['headline', 'description', 'datePublished']) {
      if (!data[field]) throw new Error(`${file} is missing ${field} in its JSON-LD`);
    }
    return {
      slug,
      url: `${SITE}/blog/${slug}`,
      title: data.headline,
      summary: data.description,
      published: data.datePublished,
      updated: data.dateModified || data.datePublished,
    };
  });
}

export function buildFeed(posts) {
  // The feed's own timestamp is the newest post's, never "now" — a rebuild
  // that changed nothing must produce a byte-identical file, or --check
  // becomes noise and nobody runs it.
  const newest = posts.map((p) => p.updated).sort().at(-1);
  const entries = posts
    .map(
      (post) => `  <entry>
    <title>${escape(post.title)}</title>
    <link href="${post.url}" />
    <id>${post.url}</id>
    <published>${post.published}T00:00:00Z</published>
    <updated>${post.updated}T00:00:00Z</updated>
    <summary>${escape(post.summary)}</summary>
  </entry>`
    )
    .join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/build-feed.js from the posts themselves. Edit the posts, not this file. -->
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>${escape(TITLE)}</title>
  <subtitle>${escape(SUBTITLE)}</subtitle>
  <link href="${SITE}/feed.xml" rel="self" />
  <link href="${SITE}/blog" />
  <id>${SITE}/blog</id>
  <updated>${newest}T00:00:00Z</updated>
  <author><name>Unify Dynamics</name><uri>${SITE}</uri></author>
  <rights>© Unify Dynamics. Quoting with attribution is welcome.</rights>
${entries}
</feed>
`;
}

// Importable without side effects — the test builds the feed in memory and
// compares it to the committed file rather than shelling out.
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  const feed = buildFeed(readPosts());
  const target = pub('feed.xml');
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : '';
    if (current !== feed) {
      console.error('public/feed.xml is out of date — run: node scripts/build-feed.js');
      process.exit(1);
    }
    console.log('public/feed.xml is in sync with the posts.');
  } else {
    fs.writeFileSync(target, feed);
    console.log(`wrote public/feed.xml — ${feed.match(/<entry>/g).length} posts`);
  }
}
